export const products = [
  {
    id: 1,
    title: "Shoes 1",
    description: "black in color",
    price: "2500",
    img: "./images/1.png",
    quantity: 1,
  },
  {
    id: 2,
    title: "Shoes 2",
    description: "Blue in color",
    price: "2300",
    img: "./images/2.png",
    quantity: 1,
  },
  {
    id: 3,
    title: "Shoes 3",
    description: "Red in color",
    price: "3500",
    img: "./images/3.png",
    quantity: 1,
  },
  {
    id: 4,
    title: "Shoes 4",
    description: "Pink in color",
    price: "90500",
    img: "./images/4.png",
    quantity: 1,
  },
  {
    id: 5,
    title: "Shoes 5",
    description: "Blue in color",
    price: "2500",
    img: "./images/5.png",
    quantity: 1,
  },
  {
    id: 6,
    title: "Shoes 6",
    description: "black in color",
    price: "3500",
    img: "./images/6.png",
    quantity: 1,
  },
  {
    id: 7,
    title: "Shoes 7",
    description: "black in color",
    price: "2500",
    img: "./images/7.png",
    quantity: 1,
  },
  {
    id: 8,
    title: "Shoes 8",
    description: "Diffeent Color",
    price: "90500",
    img: "./images/8.png",
    quantity: 1,
  },
  {
    id: 9,
    title:"Shoes 9",
    description: "Pink in color",
    price: "2500",
    img: "./images/9.png",
    quantity: 1,
  },
];
